// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wired

import (
	"github.com/google/wire"

	"github.com/ReqqQ/SocialSphereAPI/src/ui/command"
	"github.com/ReqqQ/SocialSphereAPI/src/ui/controllers"
)

// Injectors from DIContainer.go:

func InitDIContainer() (*AppService, error) {
	controllers := provideControllers()
	commands := provideCommands()
	appService := provideAppService(controllers, commands)
	return appService, nil
}

// DIContainer.go:

type AppServiceInterface interface {
	GetCommands() uicommand.CommandsInterface
	GetControllers() uicontrollers.ControllersInterface
}

type AppService struct {
	Controllers uicontrollers.Controllers
	Commands    uicommand.Commands
}

var (
	AppServiceSet = wire.NewSet(provideControllers, provideAppService, provideCommands)
)

func (a AppService) GetCommands() uicommand.CommandsInterface {
	return a.Commands
}

func (a AppService) GetControllers() uicontrollers.ControllersInterface {
	return a.Controllers
}

func provideControllers() uicontrollers.Controllers {
	return uicontrollers.Controllers{}
}

func provideCommands() uicommand.Commands {
	return uicommand.Commands{}
}

func provideAppService(controllers uicontrollers.Controllers, commands uicommand.Commands) *AppService {
	return &AppService{
		Controllers: controllers,
		Commands:    commands,
	}
}
